name: ReverseShell Build
on:
  push:
    tags:
      - "*"
      - "*/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Run Makefile
        run: make all
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
